### PR TITLE
feat: support unix shell program suspend

### LINKED ISSUE #107: suspend
I've searched through PRs and issues, didn't find this

I suspend (ctrl+z) a lot, and would love for nom to support it! Currently it doesn't react

As a maintainer I know it's not very exciting to work on a feature you (might) see as useless, so lemme draw out my workflow to show why suspending is beneficial

I'm going through my RSS feed of [terminaltrove](https://terminaltrove.com) and see a TUI that I want to try immediately. \
I (in theory) suspend nom, letting it keep all of its state; install that other tui program and try it out. \
After spending some time with it, I come back to nom using `fg` and continue on reading from the same exact spot
> "You could just close and reopen it?"

Isn't as good because once I reopen, I need to re-gain the state that I had. I need to go back to the article I was reading and open it again. Arguably that's not that much effort, but suspending lets me put in *no* effort, which is great UX. \
Also, maybe nom is currently doing a refresh; with the close and reopen method, it's in my best interest to wait for it to finish refreshing and *then* close, so that introduces another slowdown that suspending wouldn't

### PR DESCRIPTION
**Pull request by coolsloth55**
Resolves #107

Support for suspending was added to bubbletea in [v0.27.0](https://github.com/charmbracelet/bubbletea/releases/tag/v0.27.0) via [#1054](https://github.com/charmbracelet/bubbletea/pull/1054).

As far as I'm aware there's nothing handle in model when suspending and just let `fg` bring back to original list or view state.

### CODE REVIEW

**Comment by Axlefublr** [comment]
oh wow thank you! :O

**Comment by guyfedwards** [comment]
Thanks @coolsloth55 :partying_face:

**Comment by coolsloth55** [comment]
Interesting not to sure what's up with [release](https://github.com/guyfedwards/nom/actions/runs/12558697436/job/35013251336#step:6:41). At least locally with clean cache I didn't have modification of go.sum or go.mod :: 

```
Please check in your pipeline what can be changing the following files:
 M go.mod
 M go.sum
```

I'll dive into it more.

**Comment by guyfedwards** [comment]
released in [v2.7.1](https://github.com/guyfedwards/nom/releases/tag/v2.7.1)

**Pull request merged**
