### PR TITLE
Fixed fetches so they are consistent with previews

### PR DESCRIPTION
**Pull request by kanielrkirby**
Had to update two places, `commands.go` so it fetches correctly on first run, and `tui.go` so it doesn't fetch all articles when there's a feed flag passed, only the previews.

### CODE REVIEW

**Comment by guyfedwards** [comment]
@kanielrkirby looks like git has struck again 😄 Some conflict comments still in the file

**Comment by kanielrkirby** [comment]
Ahhh I'll fix it soon, I don't know how this even happened, considering I had just recloned the project.

**Comment by kanielrkirby** [comment]
Should be fixed, but I did it through `github.dev` (really neat feature btw, just changed the PR URL from `.com` to `.net` and made some changes) as I'm not at my home computer. Let me know if all is well, or if there's something wrong!

**Comment by guyfedwards** [comment]
Thanks @kanielrkirby

**Comment by kanielrkirby** [comment]
Np.

**Pull request merged**
